cache: yarn

language: node_js
node_js:
  - "6.7"

install:
  - npm install -g yarn
  - yarn install

after_script:
  - npm run flow
  - npm run lint
  - npm run danger

deploy:
  provider: script
  script: scripts/deploy_apphub.sh
  on:
    branch: master

cache:
  yarn: true
  directories:
    - node_modules
