# Use the latest macOS, mainly so
# we get Swift set up manually, otherwise we can use linux
# with swiftenv to get set up quickly, we do nothing macOS
# specific in the Dangerfile.
#
os: osx
osx_image: xcode10.1

cache:
  directories:
    # General SwiftPM
    # Danger Swift plugins, like Yams
    - .build
    - node_modules

install:
  # Grab the latest Danger JS from npm
  - nvm use 12
  - npm install -g danger
  - npm install -g yarn
  - yarn install

script:
  # Run the Dangerfile.swift
  - swift run danger-swift ci
  - yarn danger ci --verbose
