language: node_js
node_js:
  - "6.1"

install:
  - npm install

after_script:
  - npm run flow
  - npm run lint
  - npm run danger

deploy:
  provider: script
  script: scripts/deploy_apphub.sh
  on:
    branch: master