cache: yarn

language: node_js
node_js:
  - "6.7"

script:
  - scripts/deploy_commit.sh
  - yarn ci
  - yarn danger
  - scripts/deploy_apphub.sh

cache:
  yarn: true
  directories:
    - node_modules
    - .jest/cache
