version: 2
jobs:
  build-and-test:
    # Specify the Xcode version to use
    macos:
      xcode: "10.1.0"

    environment:
      ArtsyAPIClientSecret: "-"
      ArtsyAPIClientKey: "-"
      StripePublishableKey: "-"
      MapBoxAPIClientKey: "-"

      # For caching gems
      BUNDLE_PATH: vendor/bundle

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-gems-{{ checksum "Example/Gemfile.lock" }}
            # Fall back to using the latest cache if no exact match is found.
            - v1-gems-

      - run:
          name: Bundle install
          command: cd Example ; bundle check || bundle install
          environment:
            BUNDLE_JOBS: 4
            BUNDLE_RETRY: 3

      - save_cache:
          key: v1-gems-{{ checksum "Example/Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache:
          keys:
            - v1-pods-{{ checksum "Example/Podfile.lock" }}
            # Fall back to using the latest cache if no exact match is found.
            - v1-pods-

      - run:
          name: Install Yarn Dependencies
          command: yarn install --ignore-engines

      - run:
          name: Install CocoaPods
          command: cd Example ; bundle exec pod install

      - run:
          name: Package JavaScript for Testing
          command: "yarn bundle:native-ci"

      - save_cache:
          key: v1-gems-{{ checksum "Example/Podfile.lock" }}
          paths:
            - Example/Pods

      - run:
          name: Run Unit Tests
          command: cd Example ; set -o pipefail && xcodebuild -workspace Emission.xcworkspace -scheme "Emission Example" -configuration Debug test -sdk iphonesimulator -destination "platform=iOS Simulator,OS=10.3.1,name=iPhone 6" GCC_PREPROCESSOR_DEFINITIONS="\$GCC_PREPROCESSOR_DEFINITIONS RUNNING_ON_CI=1"

workflows:
  version: 2
  build-test:
    jobs:
      - build-and-test
